enum SETTINGS_ACTION_TYPES {
  SET_SLIPPAGE = 'SET_SLIPPAGE',
  SET_PREFERRED_UNIT = 'SET_UNIT',
  SET_POOLS = 'SET_POOLS',
  SET_POOL_CONFIG = 'SET_POOL_CONFIG',
  SET_WALLET = 'SET_WALLET',
  SET_POOL_CHART_DATA = 'SET_POOL_CHART_DATA',
}

export default SETTINGS_ACTION_TYPES;
